### PR TITLE
Default options to {} to avoid an exception when it's not passed in

### PR DESCRIPTION
**Pull request by marekventur**

### CODE REVIEW

**Comment by twolfson** [comment]
Looks good to me, going to wait for Travis to approve before landing

**Comment by twolfson** [comment]
Alright, Travis approved. Landing now

**Comment by twolfson** [comment]
This has been landed/released in `1.1.2`. Thanks for the helpful PRs and quick responses =)

**Comment by marekventur** [comment]
No problem, thank you for providing this package!

**Pull request merged**
