### PR TITLE
bump version of temporary to support node 0.12

### PR DESCRIPTION
**Pull request by perfectworks**

### CODE REVIEW

**Comment by twolfson** [comment]
Can we update the `.travis.yml` to test against `node@0.12` and `io.js` as well?

**Comment by perfectworks** [comment]
@twolfson done

**Comment by twolfson** [comment]
Looks good. I will land it when Travis CI passes

**Comment by twolfson** [comment]
Oh no, the `iojs` builds are failing =(

**Comment by perfectworks** [comment]
I think temporary has nothing to do this compatibility problem with iojs. The failure is more complicated :(

**Comment by twolfson** [comment]
I agree but if we are supporting `0.12`, then we should be covering `iojs` as well. Looking into it now.

**Comment by twolfson** [comment]
Ah, the version of `gm` we were on using `version` detection to figure out what stream event was best to detect the child process closing:

https://github.com/aheckmann/gm/blob/9e67d553c86a8fb12f6c1e752bbc4b52d1f0c1b5/lib/command.js#L27-L32

It looks like the latest version doesn't use that any more so an upgrade should fix this.

**Comment by twolfson** [comment]
The previously pushed version of your patch which added the `.travis.yml` and `temporary` update has been landed.

https://github.com/twolfson/gmsmith/commit/fba09d16bfc5e17ba12cee4f39519df73237d924

It looks like I was too ambiguous when I mentioned the upgrade. I went ahead and performed that fix locally. Closing the PR. Thanks for all your help!

**Pull request closed without merging**
